"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EXPTABLE = {
    post: 1,
    invitefriend: 1,
    winauction: 1,
    bid: 1,
    gainpositivefeedback: 1,
    leavefeedback: 1,
    sharecontent: 1,
    listauction: 1,
    upgradeauction: 1,
    posthighvalueitem: 1,
    winhighvalueitem: 1,
    winultrahighvalueitem: 1,
    bugreport: 1,
    constructivefeedback: 1,
    mailinglistsubcription: 1,
    followseller: 1,
    paidsubscriber: 1,
    showdownparticipation: 1,
    overtimeactivation: 1,
    overtimeparticipation: 1,
    //Daily login bonus
    dailylogin: 1,
    logoffbonus: 1,
    //Win Auction MileStones
    win1auction: 1,
    win5auction: 1,
    win10auction: 1,
    win25auction: 1,
    win50auction: 1,
    win100auction: 1,
    win250auction: 1,
    win500auction: 1,
    win1000auction: 1,
    //Upgrade Auction Milestones
    upgrade1auction: 1,
    upgrade5auction: 1,
    upgrade10auction: 1,
    upgrade25auction: 1,
    upgrade50auction: 1,
    upgrade100auction: 1,
    //Gain Positive FeedBack Milestones
    gain1positivefeedback: 1,
    gain10positivefeedback: 1,
    gain50positivefeedback: 1,
    gain100positivefeedback: 1,
    gain250positivefeedback: 1,
    gain500positivefeedback: 1,
    //Leave Feedback Milestones
    leave10feedback: 1,
    leave50feedback: 1,
    leave100feedback: 1,
    leave250feedback: 1,
    leave500feedback: 1,
    //Invite Friends Milestones
    invite1friend: 1,
    invite5friend: 1,
    invite10friend: 1,
    invite20friend: 1,
    invite30friend: 1,
    invite40friend: 1,
    invite50friend: 1,
    invite75friend: 1,
    invite100friend: 1,
    //Share Content Milestones
    share1content: 1,
    share5content: 1,
    share10content: 1,
    share25content: 1,
    share50content: 1,
    share100content: 1,
    share200content: 1,
    share300content: 1,
    share400content: 1,
    share500content: 1,
    // Dailies
    //Daily Auction Win
    win1auctiondaily: 1,
    win10auctiondaily: 1,
    win25auctiondaily: 1,
    win50auctiondaily: 1,
    //Daily Auction Listing
    list5auctiondaily: 1,
    list10auctiondaily: 1,
    list25auctiondaily: 1,
    list50auctiondaily: 1,
    list100auctiondaily: 1,
    //Daily Bug Report
    dailybugreport: 1,
    //Daily Constructive Feedback
    dailyconstructivefeedback: 1,
};
